Add support for a help flag
not-an-aardvark/lucky-commit pull request #28
Opened 2023-11-15 17:40 UTC by masklinn

When I reach for a binary I don't use often, I usually start with a `man $bin` or `bin -h` (/ `--help`) to get my bearings and ensure I don't completely misuse the thing. This currently doesn't work with lucky-commit, resulting in a laconic

> Error: hash spec contains invalid character '-' (only hex characters and underscores are allowed)

(which admittedly is better than failing silently or doing something silly).

Currently, to get the help it's necessary to be lucky enough to mistakenly give it 2 args, thus failing to match any case. I think it's not great, and having support for a help flag would be nice.

2023-11-15 17:42 UTC, orhun approved these changes

2023-11-16 00:48 UTC, not-an-aardvark requested changes
Generally LGTM, but please fix the CI error (looks like it wants you to run `cargo fmt`)

2023-11-16 17:41 UTC, masklinn commented
Ran fmt, assuming it's good now.

2023-11-17 01:32 UTC, not-an-aardvark approved these changes

2023-11-17 01:35 UTC, merged